[package]
name = "howlong"
description = "CLI duration calculator."
repository = "https://github.com/alilleybrinker/howlong"
license = "MIT"
version = "0.1.0"
rust-version = "1.56"
edition = "2021"

[dependencies]
anyhow = "1.0.0"

