[package]
name = "howlong"
version = "0.1.0"
authors = ["Andrew Lilley Brinker <andrewabrinker@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uom = "0.31.1"

